<?php if ($block->isEnabled()): ?>

<?php if ($block->getGaId()): ?>
<!-- Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<?= $block->escapeHtml($block->getGaId()) ?>"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '<?= $block->escapeHtml($block->getGaId()) ?>');
</script>
<?php endif; ?>

<?php if ($block->getFacebookPixelId()): ?>
<!-- Facebook Pixel -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '<?= $block->escapeHtml($block->getFacebookPixelId()) ?>');
fbq('track', 'PageView');
</script>
<?php endif; ?>

<?php endif; ?>
